### ISSUE TITLE
ContractNetInitiator dies when receive proposals

### ISSUE THREAD

**Issue by jonkoi** [HBRS-MAAS/project-zarvis#32]
***  Uncaught Exception for agent customer-001  ***
java.lang.NullPointerException
	at jade.proto.ContractNetInitiator.checkInSequence(ContractNetInitiator.java:324)
	at jade.proto.Initiator$3.action(Initiator.java:155)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.behaviours.CompositeBehaviour.action(CompositeBehaviour.java:109)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.behaviours.CompositeBehaviour.action(CompositeBehaviour.java:109)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
	at jade.core.Agent.run(Agent.java:1524)
	at java.lang.Thread.run(Unknown Source)
ERROR: Agent customer-001 died without being properly terminated !!!

**Comment by ani3190** [comment]
we discussed about this in the lab class and we are working on it to solve the problem
